#!/bin/bash                                                                                                                                            
printf '%o\n' $(( 5#$( echo $WATER | tr water 0123) + 5#$( echo $STIR | tr stirr                                                                       
. 0123 ) )) | tr 01234567 bestchol 
